name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build for GH Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Remove old build files
        run: |
          rm -rf docs/.vitepress/dist

      - name: Install dependencies and build
        run: |
          npm ci
          npm run generate-index
          git update-index --again
          npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/.vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
